module.exports = {
  title: "CRM Отклики",
  unread: "непрочитанных",
  total: "всего",
  sync: "Синхронизировать",
  syncing: "Синхронизация...",
  inbox: "Входящие",
  hired: "Записаны",
  rejected: "Отказ",
  all: "Все",
  vacancies: "Вакансии",
  back: "Назад к списку",
  chat: "Чат",
  loading: "Загрузка...",
  noMessages: "Сообщений нет",
  msgPlaceholder: "Сообщение...",
  searchPlaceholder: "Поиск по имени, телефону, вакансии...",
  searchVacPlaceholder: "Поиск вакансии по названию, городу, ID...",
  allIncoming: "Все входящие",
  newOnes: "Новые",
  inWork: "В работе",
  byDate: "По дате",
  unreadFirst: "Сначала непрочитанные",
  found: "Найдено",
  noResponses: "Нет откликов",
  vacancy: "Вакансия",
  status: "Статус",
  notes: "Заметки",
  notesPlaceholder: "Добавьте заметку...",
  noName: "Без имени",
  age: "Возраст",
  years: "лет",
  allStatuses: "Все статусы",
  active: "Активных",
  totalVac: "Всего",
  noVacancies: "Нет вакансий",
  addAccount: "Добавить",
  cancel: "Отмена",
  save: "Сохранить",
  nameLabel: "Название",
  deleteBtn: "Удалить",
  deleteConfirm: "Удалить аккаунт?",
  noAccounts: "Нет аккаунтов",
  avito: "Авито",
};
